export const techIcons = {
    "react": "/icons/react.png",
    "css3": "/icons/css3.png",
    "firebase": "/icons/firebase.png",
    "html5": "/icons/html5.png",
    "javascript": "/icons/javascript.png",
    "mongodb": "/icons/mongodb.png",
    "mst": "/icons/mst.png",
    "next": "/icons/next.png",
    "postgres": "/icons/postgres.png",
    "typescript": "/icons/typescript.png",
    "zustand": "/icons/zustand.png",
    "netlify": "/icons/netlify.png",
    "amazon": "/icons/amazon.png",
    "springboot": "/icons/springboot.png",
    "java": "/icons/java.png",
    "heroku": "/icons/heroku.png",
    "jwt": "/icons/jwt.svg",
    "material": "/icons/material.png",
    "redux": "/icons/redux.png",
    "p5js": "/icons/p5js.png",
    "bootstrap": "/icons/bootstrap.png",
    "tailwind": "/icons/tailwind.png",
    "cursor": "/icons/cursor.png",
    "claude": "/icons/claude.png",
    "codex": "/icons/codex.png",
    "copilot": "/icons/copilot.png",
    "warp": "/icons/warp.png",
    "trae": "/icons/trae.png",
    "notebooklm": "/icons/notebooklm.png",
    "figma": "/icons/figma.png"
}

export type TechIcon = keyof typeof techIcons